name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: General
        uses: lowlighter/metrics@latest
        if: ${{ success() || failure() }}
        with:
          token: ${{ secrets.TOKEN }}
          filename: github-metrics.svg
          base_indepth: true
          base_hireable: yes
          
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent.days: 14
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_languages_ignored: html, css, ejs 
          
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_days: 7
          plugin_wakatime_limit: 5
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_url: https://wakapi.dev
          plugin_wakatime_user: current
      - name: General_Right
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: general_2.svg
          token: ${{ secrets.TOKEN }}
          base: ""
          
          plugin_notable: yes
          plugin_isocalendar: yes
          
          plugin_sponsors: yes
          plugin_sponsors_past: yes
          plugin_sponsorships_sections: amount
          
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 0
          plugin_activity_filter: issue, pr, release, fork, review, ref/create
